//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBPIC
    {
        public int ID { get; set; }
        public string MAP_AC_NM { get; set; }
        public string IMG_NM { get; set; }
        public string IMG_URL { get; set; }
        public string IMG_LINK { get; set; }
        public string FILE_PATH { get; set; }
        public System.DateTime UP_DT { get; set; }
        public int UP_USR_ID { get; set; }
        public string UP_MODE { get; set; }
        public int SR_SQ { get; set; }
        public int MAP_NEWS_ID { get; set; }
        public int MAP_PRODUCT_ID { get; set; }
        public int MAP_WORKS_ID { get; set; }
    }
}
