//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBPRODUCTTYPE
    {
        public int ID { get; set; }
        public string LANG_CD { get; set; }
        public string PRD_TP_NM { get; set; }
        public int SR_SQ { get; set; }
        public string PRD_TP_ST { get; set; }
        public int BUD_ID { get; set; }
        public System.DateTime BUD_DT { get; set; }
        public Nullable<int> UPD_USR_ID { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    }
}
