//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBUSR
    {
        public int ID { get; set; }
        public string SIGNIN_ID { get; set; }
        public string SIGNIN_PWD { get; set; }
        public string USR_NM { get; set; }
        public string USR_ENM { get; set; }
        public string USR_EML { get; set; }
        public string USR_GUID { get; set; }
        public System.DateTime SIGNIN_DTM { get; set; }
        public int BUD_USRID { get; set; }
        public System.DateTime BUD_DTM { get; set; }
        public int UPD_USRID { get; set; }
        public System.DateTime UPD_DTM { get; set; }
    }
}
